#
# This build file is used by AWS CodeBuild to run our build, produce a snap and make it available to downstream
# CodePipeline stages.
#
version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
      - dotnet publish
artifacts:
  files:
    - '**/*'